# directory configurations - change the below three lines as appropriate
dir_ckpt: "/home/myb/project12_11/ckpt"  # Change this to your checkpoint directory.
dir_dataset: "/home/myb/datasets/cityscapes"  # Change this to your dataset directory.
#dir_pseudo_masks: "/users/gyungin/reco/ckpt/cityscapes/train/reco/deit_s_16_sin_in_train_ce_ta_dc/k050/dt_crf"
# "/users/gyungin/denseclip/analysis/reco/cosegmentation/ckpt_v3/cityscapes_train/deit_s_16_sin_in_train_ce_ta/k050/dt_crf"

dataset_name: "cityscapes"  # ["cityscapes", "coco_stuff", "kitti_step"]

# hyperparameters for networks
batch_size: 16
iter_val: 1000
n_workers: 16
segmentor_name: "mysegmentor"  # ["deeplabv3plus_resnet101", "deeplabv3plus_resnet50", "deeplabv3plus_mobilenet"]
